[package]
name = "galileo"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Penumbra dependencies
penumbra-proto = { git = "https://github.com/penumbra-zone/penumbra" }
penumbra-crypto = { git = "https://github.com/penumbra-zone/penumbra" }
penumbra-wallet = { git = "https://github.com/penumbra-zone/penumbra" }
penumbra-transaction = { git = "https://github.com/penumbra-zone/penumbra" }

# External dependencies
ark-ff = "0.3"
ark-serialize = "0.3"
anyhow = "1"
directories = "4.0.1"
regex = "1"
serenity = { version = "0.10", default-features = false, features = ["client", "cache", "gateway", "rustls_backend", "model"] }
sqlx = { version = "0.5", features = [ "runtime-tokio-rustls", "postgres", "offline" ] }
tracing = "0.1"
tracing-subscriber = "0.2"
tokio = { version = "1", features = ["full"] }
humantime = "2"
clap = { version = "3", features = ["derive"] }
serde_json = "1"
tonic = "0.6"
futures = "0.3"
derivative = "2"
fslock = "0.2"
rand = "0.8"
reqwest = "0.11"
indexmap = "1.8"
async-stream = "0.3"
chrono = "0.4"
serde = "1"
csv-stream = "0.1"
